#!/usr/bin/env bash

## ggtool ansiblog

if [[ -t 0 ]]; then
  echo -e "\nUsage: [piped Ansible log file] | ansiblog\n"
else
  sed -E 's/(^COMMAND.*$)/'$'\e''[1;30;105m\1'$'\e''[0m/g;
          s/^[0-9-]*.*n=ansible \|/'$'\e''[0m/g;
          s/(ok: \[)/'$'\e''[32m\1/g;
          s/(skipping: \[)/'$'\e''[36m\1/g;
          s/(changed: \[)/'$'\e''[33m\1/g;
          s/(fatal: \[|\[ERROR\])/'$'\e''[1;91m\1/g;
          s/(<[0-9.]*[0-9]>)/'$'\e''[2;34m\1/g;
          s/(TASK.*\*\*\*\*$)/'$'\e''[1;35m\1/g;
          s/(PLAY.*\*\*\*\*$)/'$'\e''[1;95m\1/g;
          '
  tint
fi