#!/usr/bin/env bash

rowregex='exe=[^ ]*' # Default regex - example from audit.log
colregex='acct=[^ ]*'
headerfilter='"[^"]*"'

function macro () {
  echo "$1" | sed -E 's/%(day|DAY)%/^[A-Z][a-z]{2} +[0-9]+/g;
  s/%(hour|HOUR)%/^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}/g;
  s/%(tenmin|TENMIN)%/^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}:[0-9]/g;
  s/%(min|MIN)%/^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}:[0-9]{2}/g;
  s/%(ip|IP)%/[0-9]{1,3}\\.[0-9]{1,3}\.[0-9]{1,3}\\.[0-9]{1,3}/g'
}

function row () {
  # echo -en "\e[1m$1\e[0m¬"
  for colmatch in "${colmatches[@]}"; do
    cell=$(cat $tempfile | grep $2 -EI "$1" 2>/dev/null | grep -EIc "$colmatch")
    echo -n "$cell¬"
  done
  nomatch=$(cat $tempfile | grep $2 -EI "$1" 2>/dev/null | grep -EIvc $colregex )
  echo "$nomatch"
  # tot=$(cat $tempfile | grep $2 -EIc "$1" 2>/dev/null)
}

if [[ $# -ge 2  ]]; then
  rowregex="$(macro $1)"
  colregex="$(macro $2)"
fi

tempfile=$(mktemp /tmp/XXXXXX)
if [[ -z $logfiles ]]; then
  cat > $tempfile
else
  cat $logfiles > $tempfile
fi

# DEBUG

echo "rowregex = $rowregex"
echo "colregex = $colregex"
exit
{
  IFS=$'\n'
  rowmatches=( $(cat $tempfile | grep -EIo "$rowregex" 2>/dev/null | sort | uniq) )
  colmatches=( $(cat $tempfile | grep -EIo "$colregex" 2>/dev/null | sort | uniq) )
  for dot in "${rowmatches[@]}"; do
    echo -n "□" >&2
  done
  echo -en "\e[1G\e[1m --- "
  for header in "${colmatches[@]}"; do
    # echo -n "¬${header:(-10):10}"
    header="$(echo -n $header | grep -o $headerfilter)"
    echo -n "¬${header}"
  done
  echo -e "¬(No Match)\e[0m"
  echo -en "\e[1G" >&2
  for rowmatch in "${rowmatches[@]}"; do
    echo -n '■' >&2
    echo -en "\e[1m${rowmatch}\e[0m¬"
    row $rowmatch
  done
  echo -en "\e[1m(No Match)\e[0m¬"
  row $rowregex -v
} | column -s¬ -t
rm -f $tempfile


## ggtool
