#!/usr/bin/env bash

## ggtool logstat

[[ -x $(which 'rg') ]] && greptool='rg' || greptool='egrep' #          rg = ripgrep. See https://github.com/BurntSushi/ripgrep

echo | column -t -R 1 &>/dev/null && align="-R 2,3,4,5,6,7" # Because some versions of column lack the -R flag

[[ $1 == '-i' ]] && shift && i='i'
[[ $# -gt 0 ]] && regex="$1"

# Macros 
regex="$(echo $regex | sed -E 's/%(ov|OV|opsview)%/ opsview\.[a-z]*/g;
  s/%(ip|IP)%/[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}/g;
  s/%(uuid|UUID)%/[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}/g')"
tempfile=$(mktemp /tmp/XXXXXX)
if [[ -z $logfiles ]]; then
  cat > $tempfile
else
  cat $logfiles > $tempfile
fi

function row () {
  tot=$(cat $tempfile | $greptool $2 -I${i}c "$1" 2>/dev/null)
  err=$(cat $tempfile | $greptool $2 -I${i} "$1" 2>/dev/null | $greptool -I${i}c '\[(ERR|ERROR|FATAL|CRIT|CRITICAL)\]' )
  warn=$(cat $tempfile | $greptool $2 -I${i} "$1" 2>/dev/null | $greptool -I${i}c '\[(WARN|WARNING)\]' )
  info=$(cat $tempfile | $greptool $2 -I${i} "$1" 2>/dev/null | $greptool -I${i}c '\[(INFO|NOTICE)\]' )
  debug=$(cat $tempfile | $greptool $2 -I${i} "$1" 2>/dev/null | $greptool -I${i}c '\[DEBUG\]' )
  other=$(cat $tempfile | $greptool $2 -I${i} "$1" 2>/dev/null | $greptool -I${i}vc '\[(DEBUG|ERR|ERROR|FATAL|CRIT|CRITICAL|WARN|WARNING|INFO|NOTICE)\]' )
  echo -e "\e[1;91m$err\e[0m¬\e[1;33m$warn\e[0m¬$info¬\e[34m$debug\e[0m¬\e[2m$other\e[0m¬\e[1m$tot\e[0m"
}

{
  echo -e "\e[1G\e[1mSearch Term¬Error¬Warning¬Info¬Debug¬Other¬Total\e[0m"
  IFS=$'\n'
  if [[ -n $regex ]]; then
    matches=$(cat $tempfile | $greptool -I${i}o "$regex" 2>/dev/null | sort | uniq)
  else
    matches=$(cat $tempfile | sed 's/journal://' | awk '{print $5}' 2>/dev/null | sed -E 's/\[[0-9]*\]//g' | sort | uniq)
  fi
  for dot in $matches; do
    echo -n "□" >&2
  done
  echo -en "\e[1G" >&2
    for match in $matches; do
    echo -n '■' >&2
    echo -n "$match¬"
    row $match
  done
  echo -n "(No Match)¬"
  row $regex -v
} | column -s¬ -t $align

rm -f $tempfile
