#!/usr/bin/env bash

## ggtool logstat

regex='\bopsview\.[a-z]*' # Default regex - selects Opsview components

while [[ $# > 0 ]]; do
  case "${1,,}" in
    -r | --regex   ) shift; regex="$1" ;;
    -i | --ip ) regex="[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}" ;;
    -t | --time    )
      case "${2,,}" in
        d | day ) shift; regex="^[A-Z][a-z]{2} +[0-9]+" ;;
        h | hour) shift; regex="^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}" ;;
        t | ten ) shift; regex="^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}:[0-9]" ;;
        m | min ) shift; regex="^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}:[0-9]{2}" ;;
        * ) echo "Invalid time \"$2\"" >&2 ;;
      esac
    ;;
    -* ) echo "Invalid option \"$1\"" >&2 ;;
    *)
      logfiles="$logfiles $1"
    ;;
  esac
  shift
done

tempfile=$(mktemp /tmp/XXXXXX)
if [[ -z $logfiles ]]; then
  cat > $tempfile
else
  cat $logfiles > $tempfile
fi

function row () {
  tot=$(cat $tempfile | grep -EIc "$1" 2>/dev/null)
  err=$(cat $tempfile | grep -EI "$1" 2>/dev/null | grep -EIc '\[(ERR|ERROR)\]' )
  warn=$(cat $tempfile | grep -EI "$1" 2>/dev/null | grep -EIc '\[(WARN|WARNING)\]' )
  info=$(cat $tempfile | grep -EI "$1" 2>/dev/null | grep -EIc '\[(INFO|NOTICE)\]' )
  debug=$(cat $tempfile | grep -EI "$1" 2>/dev/null | grep -EIc '\[DEBUG\]' )
  other=$(cat $tempfile | grep -EI "$1" 2>/dev/null | grep -EIvc '\[(DEBUG|ERR|ERROR|WARN|WARNING|INFO|NOTICE)\]' )
  echo -e "\e[1;91m$err\e[0m,\e[1;33m$warn\e[0m,$info,\e[34m$debug\e[0m,\e[2m$other\e[0m,\e[1m$tot\e[0m"
}


{
  echo -e "\e[1G\e[1mGrouping,Error,Warning,Info,Debug,Other,Total\e[0m"
  IFS=$'\n'
  matches=$(cat $tempfile | grep -EIo "$regex" 2>/dev/null | sort | uniq)
    for dot in $matches; do
    echo -n "_" >&2
  done
  echo -en "\e[1G" >&2
    for match in $matches; do
    echo -n '.' >&2
    # tot=$(cat $tempfile | grep -Ic "$match" 2>/dev/null)
    # err=$(cat $tempfile | grep -I "$match" 2>/dev/null | grep -EIc '\[(ERR|ERROR)\]' )
    # warn=$(cat $tempfile | grep -I "$match" 2>/dev/null | grep -EIc '\[(WARN|WARNING)\]' )
    # info=$(cat $tempfile | grep -I "$match" 2>/dev/null | grep -EIc '\[(INFO|NOTICE)\]' )
    # debug=$(cat $tempfile | grep -I "$match" 2>/dev/null | grep -EIc '\[DEBUG\]' )
    # other=$(cat $tempfile | grep -I "$match" 2>/dev/null | grep -EIvc '\[(DEBUG|ERR|ERROR|WARN|WARNING|INFO|NOTICE)\]' )
    # echo -e "$match,\e[1;91m$err\e[0m,\e[1;33m$warn\e[0m,$info,\e[34m$debug\e[0m,\e[2m$other\e[0m,\e[1m$tot\e[0m"
    echo -n "$match,"
    row $match
  done
  # tot=$(cat $tempfile | grep -EIc "$regex" 2>/dev/null)
  # err=$(cat $tempfile | grep -I "$regex" 2>/dev/null | grep -EIc '\[(ERR|ERROR)\]' )
  # warn=$(cat $tempfile | grep -I "$regex" 2>/dev/null | grep -EIc '\[(WARN|WARNING)\]' )
  # info=$(cat $tempfile | grep -I "$regex" 2>/dev/null | grep -EIc '\[(INFO|NOTICE)\]' )
  # debug=$(cat $tempfile | grep -I "$regex" 2>/dev/null | grep -EIc '\[DEBUG\]' )
  # other=$(cat $tempfile | grep -I "$regex" 2>/dev/null | grep -EIvc '\[(DEBUG|ERR|ERROR|WARN|WARNING|INFO|NOTICE)\]' )
  # echo -e "(Other),\e[1;91m$err\e[0m,\e[1;33m$warn\e[0m,$info,\e[34m$debug\e[0m,\e[2m$other\e[0m,\e[1m$tot\e[0m"
  echo -n "(Other),"
  row $regex
} | column -s, -t -R 2,3,4,5,6,7

rm -f $tempfile
