#!/usr/bin/env bash

## ggtool logstat

regex='\bopsview\.[a-z]*' # Default regex - selects Opsview components

echo | column -t -R 1 &>/dev/null && align="-R 2,3,4,5,6,7" # Because some versions of column lack the -R flag

[[ $# -gt 0 ]] && regex="$1"

# Macros 
regex="$(echo $regex | sed -E 's/%(day|DAY)%/^[A-Z][a-z]{2} +[0-9]+/g;
  s/%(hour|HOUR)%/^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}/g;
  s/%(tenmin|TENMIN)%/^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}:[0-9]/g;
  s/%(min|MIN)%/^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}:[0-9]{2}/g;
  s/%(ip|IP)%/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/g')"

tempfile=$(mktemp /tmp/XXXXXX)
if [[ -z $logfiles ]]; then
  cat > $tempfile
else
  cat $logfiles > $tempfile
fi

function row () {
  tot=$(cat $tempfile | grep $2 -EIc "$1" 2>/dev/null)
  err=$(cat $tempfile | grep $2 -EI "$1" 2>/dev/null | grep -EIc '\[(ERR|ERROR)\]' )
  warn=$(cat $tempfile | grep $2 -EI "$1" 2>/dev/null | grep -EIc '\[(WARN|WARNING)\]' )
  info=$(cat $tempfile | grep $2 -EI "$1" 2>/dev/null | grep -EIc '\[(INFO|NOTICE)\]' )
  debug=$(cat $tempfile | grep $2 -EI "$1" 2>/dev/null | grep -EIc '\[DEBUG\]' )
  other=$(cat $tempfile | grep $2 -EI "$1" 2>/dev/null | grep -EIvc '\[(DEBUG|ERR|ERROR|WARN|WARNING|INFO|NOTICE)\]' )
  echo -e "\e[1;91m$err\e[0m¬\e[1;33m$warn\e[0m¬$info¬\e[34m$debug\e[0m¬\e[2m$other\e[0m¬\e[1m$tot\e[0m"
}

{
  echo -e "\e[1G\e[1mGrouping¬Error¬Warning¬Info¬Debug¬Other¬Total\e[0m"
  IFS=$'\n'
  matches=$(cat $tempfile | grep -EIo "$regex" 2>/dev/null | sort | uniq)
    for dot in $matches; do
    echo -n "□" >&2
  done
  echo -en "\e[1G" >&2
    for match in $matches; do
    echo -n '■' >&2
    echo -n "$match¬"
    row $match
  done
  echo -n "(No Match)¬"
  row $regex -v
} | column -s¬ -t $align

rm -f $tempfile
