#!/usr/bin/env bash

## ggtool uninstall-ggtools

grep -Ir '#.*ggtool' /usr/bin/ | cut -d: -f1 | grep -v uninstall-ggtools | xargs -I% -P1 rm -f %
echo "ggtools uninstalled"
rm -f /usr/bin/uninstall-ggtools