#!/usr/bin/env bash

# 🦞

regex='\bopsview\.[a-z]*'
excluderegex='^$'
long=0

# Usage logster [options] logfile [logfile...]) #helptext
#)#helptext

while [[ $# > 0 ]]; do
  case "${1,,}" in
    -h | --help         ) cat $0 | grep '#helptext' | grep -o '^[^)]*' && exit ;;
    -l | --long         ) long=1 ;; #helptext
    -g | --group        ) shift; regex="$1" ;; #helptext
    -x | --exclude      ) shift; excluderegex="$1" ;; #helptext
    -f | --filter       ) shift; filterregex="$1" ;; #helptext
    -c | --component    ) regex='\bopsview\.[a-z]*' ;; #helptext
    -s | --subcomponent ) regex='\bopsview\.[a-z.]*[a-z]' ;; #helptext
    -t | --time ) #helptext
      case "${2,,}" in
        d | day ) shift; regex="^[A-Z][a-z]{2} +[0-9]+" ;; #helptext
        h | hour) shift; regex="^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}" ;; #helptext
        t | ten ) shift; regex="^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}:[0-9]" ;; #helptext
        m | min ) shift; regex="^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}:[0-9]{2}" ;; #helptext
        * ) echo "Invalid time period \"$2\"" >&2 ;;
      esac
    ;;
    -* ) echo "Invalid option \"$1\"" >&2 ;;
    *)
      logfiles="$logfiles $1"
    ;;
  esac
  shift
done

tempdir=$(mktemp -d /tmp/XXXXXX)
if [[ -z $logfiles ]]; then
  cat > $tempdir/log
else
  cat ${logfiles# } > $tempdir/log
fi

function row () {
  tot=$(cat $tempdir/$2 | grep -c "$1")
  err=$(cat $tempdir/$2 | grep "$1" | grep -Ec '\[(ERR|ERROR)\]' )
  warn=$(cat $tempdir/$2 | grep "$1" | grep -Ec '\[(WARN|WARNING)\]' )
  info=$(cat $tempdir/$2 | grep "$1" | grep -Ec '\[(INFO|NOTICE)\]' )
  debug=$(cat $tempdir/$2 | grep "$1" | grep -Ec '\[DEBUG\]' )
  other=$(cat $tempdir/$2 | grep "$1" | grep -Evc '\[(DEBUG|ERR|ERROR|WARN|WARNING|INFO|NOTICE)\]' )
  echo -en "$1,\e[1;91m$err\e[0m,\e[1;33m$warn\e[0m,"
  [[ $long -eq 1 ]] && echo -en "$info,\e[34m$debug\e[0m,\e[2m$other\e[0m,"
  echo -e "\e[1m$tot\e[0m"
}


{
  echo -en "\e[1mGrouping,Error,Warning,"
  [[ $long -eq 1 ]] && echo -en "Info,Debug,Other,"
  echo -e "Total\e[0m"
  IFS=$'\n'
  for match in $(cat $tempdir/log | grep -Ev "$excluderegex" |  grep -E "$filterregex" |  grep -Eo "$regex" | sort | uniq); do
    row $match log
  done
  cat $tempdir/log | grep -Ev "$excluderegex" |  grep -E "$filterregex" |  grep -Ev "$regex" > $tempdir/inverselog
  row '.*' inverselog
} | sed "s/\.\*/(Other)/" | column -s, -t -R 2,3,4,5,6,7
rm -rf $tempdir


# ⠀⠀⠀⠀⣀⣠⣤⣶⠶⠶⣶⣦⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
# ⠀⠀⣠⡾⠛⠉⠀⠀⠀⠀⠀⠀⠉⠛⠿⣦⡀⠀⠀⠀⠀⠀⠀╭──────────────────────────────────────────────╮
# ⠀⣼⠟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣆⠀⠀⠀⠀⠀│⠀Always with the logfiles! WOOP Woop woop woop│
# ⢠⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣇⠀⠀⠀⠀╰─╮ 🮣──────────────────────────────────────────╯
# ⢸⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣄⡀⠀⠀⠀ │🮣🮠
# ⠈⣿⠀⠀⠀⠀⠀⠀⣤⡶⠿⠷⣦⣄⠀⠀⢀⣤⣤⣽⣷⠀⠀⠀
# ⠀⢿⡄⠀⠀⠀⠀⣼⡏⠀⠀⣀⠈⣿⡄⢀⣿⠁⠀⢀⡙⣷⠀⠀
# ⠀⠘⣷⠀⠀⠀⠀⠹⣧⡀⠀⠉⣠⣿⠃⠸⣿⡀⠀⠈⣡⣿⠀⠀
# ⠀⠀⣿⡇⠀⠀⠀⢀⡙⠛⠿⠿⠛⠁⠀⠀⠻⣿⡿⢿⣿⠁⠀⠀
# ⠀⠀⢻⡇⠀⠀⠀⠙⠻⢶⣶⠾⠃⠀⠀⠀⠀⠙⠻⣾⣿⡀⠀⠀
# ⠀⠀⢸⡇⠀⠀⠀⠀⠀⢀⣄⠀⠀⢀⠀⠀⢀⠀⢀⣄⠙⢿⣄⠀
# ⠀⠀⢸⡇⠀⠀⠀⠀⠀⠀⢹⣇⠀⢹⣷⠀⢹⣇⠀⢹⡇⠀⣿⡀
# ⠀⠀⢸⡇⠀⠀⠀⠀⠀⠀⠸⣿⠀⢸⣿⠀⠘⣿⠀⢸⣿⢀⣿⠇
# ⠀⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⣿⠀⢸⣿⠀⢀⣿⣀⣸⡿⠛⠋⠀
# ⠀⠀⠸⠇⠀⠀⠀⠀⠀⠀⠀⠙⠿⠟⠛⠿⠿⠋⠙⠉⠀⠀⠀⠀
