#!/usr/bin/env bash

regex='\bopsview\.[a-z]*'

while [[ $# > 0 ]]; do
  case "${1,,}" in
    -r | --regex ) shift; regex="$1" ;;
    -t | --time  )
      case "${2,,}" in
        d | day ) shift; regex="^[A-Z][a-z]{2} +[0-9]+" ;;
        h | hour) shift; regex="^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}" ;;
        t | ten ) shift; regex="^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}:[0-9]" ;;
        m | min ) shift; regex="^[A-Z][a-z]{2} +[0-9]+ +[0-9]{2}:[0-9]{2}" ;;
        * ) echo "Invalid time \"$2\"" >&2 ;;
      esac
    ;;
    -* ) echo "Invalid option \"$1\"" >&2 ;;
    *)
      logfiles="$logfiles $1"
    ;;
  esac
  shift
done

tempfile=$(mktemp /tmp/XXXXXX)
if [[ -z $logfiles ]]; then
  cat > $tempfile
else
  cat $logfiles > $tempfile
fi

{
  echo -e "\e[1mGrouping,Error,Warning,Total\e[0m"
  IFS=$'\n'
  for match in $(cat $tempfile | grep -Eo "$regex" | sort | uniq); do
    tot=$(cat $tempfile | grep -c "$match")
    err=$(cat $tempfile | grep "$match" | grep -Ec '\[(ERR|ERROR)\]' )
    warn=$(cat $tempfile | grep "$match" | grep -Ec '\[(WARN|WARNING)\]' )
    echo -e "$match,\e[1;91m$err\e[0m,\e[1;33m$warn\e[0m,\e[1m$tot\e[0m"
  done
  tot=$(cat $tempfile | grep -Evc "$regex")
  err=$(cat $tempfile | grep -Ev "$regex" | grep -Ec '\[(ERR|ERROR)\]' )
  warn=$(cat $tempfile | grep -Ev "$regex" | grep -Ec '\[(WARN|WARNING)\]' )
  echo -e "(Other),\e[1;91m$err\e[0m,\e[1;33m$warn\e[0m,\e[1m$tot\e[0m"
} | column -s, -t -R 2,3,4

rm -f $tempfile
